name: LodestonePorter
version: 1.1.1
author: PhoenixofForce
api-version: 1.21
main: lodestone.Main
commands:
  lp:
    description: Opens the tp menu from anywhere in the world
    usage: /lp

permissions:
  createTP:
    description: Allows you to create teleporters.
    default: true
  breakAllTP:
    description: Allows you to break teleporters from other player, ignoring config settings.
    default: op
  useTP:
    description: Allows you to use teleporter.
    default: true
  ignoreCosts:
    description: Allows you to ignore the costs set in the config
    default: false
  useTPAnywhere:
    description: Allows you to use /tp
    default: true